# Generated by Django 4.0.4 on 2022-05-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=3)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=128, verbose_name='address')),
            ],
        ),
    ]
