# Generated by Django 4.0.4 on 2022-05-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formTaskApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicform',
            name='age',
            field=models.IntegerField(),
        ),
    ]
