# Generated by Django 4.0.4 on 2022-05-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formTaskApp', '0003_alter_basicform_address_alter_basicform_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicform',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
