# Generated by Django 4.0.4 on 2022-05-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formTaskApp', '0004_alter_basicform_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicform',
            name='address',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='basicform',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='basicform',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='basicform',
            name='phoneNumber',
            field=models.CharField(max_length=12),
        ),
    ]
