# Generated by Django 3.2.6 on 2022-05-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formTaskApp', '0005_alter_basicform_address_alter_basicform_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicform',
            name='phoneNumber',
            field=models.IntegerField(max_length=10),
        ),
    ]
