# Generated by Django 3.2.6 on 2022-05-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formTaskApp', '0007_alter_basicform_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicform',
            name='phoneNumber',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
